name: Robot Framework CI with Virtual Environment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest  # Use a more stable runner image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python --version

    - name: Upgrade pip and install dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Robot Framework and Dependencies
      run: |
        source venv/bin/activate
        pip install robotframework
        pip install robotframework-requests
        pip install robotframework-jsonlibrary
        pip install robotframework-collections

    - name: Run Robot Framework tests
      run: |
        source venv/bin/activate
        robot path/to/your/testfile.robot

    - name: Upload test results as artifacts
      uses: actions/upload-artifact@v2  # Use v2 for compatibility
      with:
        name: robot-test-results
        path: output.xml

